/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useState, useEffect, useRef, ChangeEvent, KeyboardEvent } from 'react';
import { Camera, Upload, Copy, Check, Trash2, Plus, Search, Edit2, Download } from 'lucide-react';
// Corrección 1: Importación estándar de framer-motion
import { motion, AnimatePresence } from 'framer-motion'; 
import { extractColors, PaletteEntry } from './utils';

const STORAGE_KEY = 'colorpicker_collection';

type SortOrder = 'newest' | 'oldest';

// Corrección 2: Eliminada la prop 'key' de la interfaz (React la maneja internamente)
interface PaletteCardProps {
  palette: PaletteEntry;
  onDelete: (id: string) => void;
  onUpdateName: (id: string, name: string) => void;
  onCopy: (hex: string, id: string) => void;
}

function PaletteCard({ 
  palette, 
  onDelete, 
  onUpdateName,
  onCopy 
}: PaletteCardProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [tempName, setTempName] = useState(palette.name || '');
  const [copiedHex, setCopiedHex] = useState<string | null>(null);

  const handleCopy = (hex: string) => {
    onCopy(hex, palette.id);
    setCopiedHex(hex);
    setTimeout(() => setCopiedHex(null), 2000);
  };

  const handleBlur = () => {
    setIsEditing(false);
    onUpdateName(palette.id, tempName);
  };

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'Enter') {
      handleBlur();
    }
  };

  const exportAsPNG = () => {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const width = 1200;
    const height = 800;
    const padding = 60;
    const swatchHeight = 500;

    canvas.width = width;
    canvas.height = height;

    // Background
    ctx.fillStyle = '#FFFFFF';
    ctx.fillRect(0, 0, width, height);

    // Title
    ctx.fillStyle = '#343A40';
    ctx.font = '400 48px sans-serif';
    ctx.fillText(palette.name || 'Untitled Palette', padding, padding + 40);

    // Date
    const dateStr = new Date(palette.timestamp).toLocaleDateString();
    ctx.fillStyle = '#ADB5BD';
    ctx.font = '24px monospace';
    ctx.fillText(dateStr, width - padding - ctx.measureText(dateStr).width, padding + 40);

    // Swatches
    const swatchWidth = (width - (padding * 2)) / palette.colors.length;
    palette.colors.forEach((hex, i) => {
      const x = padding + (i * swatchWidth);
      const y = padding + 100;

      ctx.fillStyle = hex;
      ctx.fillRect(x, y, swatchWidth, swatchHeight);

      ctx.fillStyle = '#343A40';
      ctx.font = 'bold 32px monospace';
      const hexText = hex.toUpperCase();
      const textWidth = ctx.measureText(hexText).width;
      ctx.fillText(hexText, x + (swatchWidth / 2) - (textWidth / 2), y + swatchHeight + 60);
    });

    // Branding
    ctx.fillStyle = '#DEE2E6';
    ctx.font = '18px monospace';
    const brand = 'GENERATED BY COLOR PICKER';
    ctx.fillText(brand, width / 2 - ctx.measureText(brand).width / 2, height - 40);

    // Download
    const link = document.createElement('a');
    link.download = `${palette.name || 'palette'}-${palette.id.slice(0, 8)}.png`;
    link.href = canvas.toDataURL('image/png');
    link.click();
  };

  const formattedDate = new Date(palette.timestamp).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  });

  return (
    <motion.article
      layout
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, scale: 0.95 }}
      className="bg-white rounded-3xl overflow-hidden shadow-sm border border-black/5 group"
    >
      <div className="relative aspect-[16/9] overflow-hidden">
        <img 
          src={palette.image} 
          alt={palette.name || 'Palette'} 
          className="w-full h-full object-cover"
          referrerPolicy="no-referrer"
        />
        <div className="absolute top-4 right-4 flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
          <button 
            onClick={exportAsPNG}
            className="p-2 rounded-full bg-black/20 backdrop-blur-md text-white hover:bg-yellow-500 transition-colors"
            title="Export as PNG"
          >
            <Download className="w-4 h-4" />
          </button>
          <button 
            onClick={() => onDelete(palette.id)}
            className="p-2 rounded-full bg-black/20 backdrop-blur-md text-white hover:bg-red-500 transition-colors"
            title="Delete Palette"
          >
            <Trash2 className="w-4 h-4" />
          </button>
        </div>
      </div>
      
      <div className="p-5">
        <div className="mb-6">
          {isEditing ? (
            <input
              autoFocus
              type="text"
              value={tempName}
              onChange={(e) => setTempName(e.target.value)}
              onBlur={handleBlur}
              onKeyDown={handleKeyDown}
              className="w-full text-lg font-normal bg-transparent border-b border-yellow-500 outline-none pb-1"
            />
          ) : (
            <div 
              onClick={() => setIsEditing(true)}
              className="flex items-center gap-2 cursor-pointer group/name"
            >
              <h3 className={`text-lg font-normal ${!palette.name ? 'text-black/30 italic' : 'text-black/80'}`}>
                {palette.name || 'Untitled Palette'}
              </h3>
              <Edit2 className="w-3 h-3 text-black/20 opacity-0 group-hover/name:opacity-100 transition-opacity" />
            </div>
          )}
        </div>

        <div className="flex gap-3 mb-6">
          {palette.colors.map((hex, index) => (
            <div key={`${palette.id}-${hex}-${index}`} className="flex-1 flex flex-col items-center gap-2">
              <button
                onClick={() => handleCopy(hex)}
                className="w-full aspect-square rounded-xl relative group/color transition-transform active:scale-95 shadow-inner"
                style={{ backgroundColor: hex }}
                title={`Copy ${hex}`}
              >
                <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover/color:opacity-100 transition-opacity">
                  {copiedHex === hex ? (
                    <Check className="w-5 h-5 text-white mix-blend-difference" />
                  ) : (
                    <Copy className="w-5 h-5 text-white mix-blend-difference" />
                  )}
                </div>
              </button>
              <span className="text-[10px] font-mono text-black/40 uppercase tracking-tighter">
                {hex}
              </span>
            </div>
          ))}
        </div>
        
        <div className="flex justify-center pt-2 border-t border-black/5">
          <span className="text-[10px] font-mono text-black/20 uppercase tracking-widest">
            {formattedDate}
          </span>
        </div>
      </div>
    </motion.article>
  );
}

export default function App() {
  const [palettes, setPalettes] = useState<PaletteEntry[]>([]);
  const [isUploading, setIsUploading] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [sortOrder, setSortOrder] = useState<SortOrder>('newest');
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved) {
      try {
        setPalettes(JSON.parse(saved));
      } catch (e) {
        console.error('Failed to parse saved palettes', e);
      }
    }
  }, []);

  const savePalettes = (newPalettes: PaletteEntry[]) => {
    setPalettes(newPalettes);
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(newPalettes));
    } catch (e) {
      console.error('localStorage quota exceeded. Try deleting some palettes.', e);
    }
  };

  const handleFileUpload = (e: ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) processFile(file);
  };

  const processFile = async (file: File) => {
    setIsUploading(true);
    const reader = new FileReader();
    
    reader.onload = async (event) => {
      try {
        const base64 = event.target?.result as string;
        const colors = await extractColors(base64);
        
        const newEntry: PaletteEntry = {
          id: crypto.randomUUID(),
          name: '',
          image: base64,
          colors,
          timestamp: Date.now(),
        };

        // Usamos el updater funcional para evitar el stale closure
        setPalettes(prev => {
          const updated = [newEntry, ...prev];
          try {
            localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
          } catch (e) {
            console.error('localStorage quota exceeded. Try deleting some palettes.', e);
          }
          return updated;
        });
      } catch (error) {
        console.error('Error extracting colors:', error);
      } finally {
        setIsUploading(false);
      }
    };
    reader.readAsDataURL(file);
  };

  const updatePaletteName = (id: string, name: string) => {
    const updated = palettes.map(p => p.id === id ? { ...p, name } : p);
    savePalettes(updated);
  };

  const deletePalette = (id: string) => {
    const filtered = palettes.filter(p => p.id !== id);
    savePalettes(filtered);
  };

  const handleCopy = (hex: string) => {
    navigator.clipboard.writeText(hex);
  };

  const filteredAndSortedPalettes = palettes
    .filter(p => (p.name || 'Untitled Palette').toLowerCase().includes(searchQuery.toLowerCase()))
    .sort((a, b) => {
      return sortOrder === 'newest' ? b.timestamp - a.timestamp : a.timestamp - b.timestamp;
    });

  return (
    <div className="min-h-screen bg-[#F8F9FA] text-[#343A40] font-sans selection:bg-yellow-100">
      <header className="sticky top-0 z-20 bg-white/80 backdrop-blur-md border-b border-black/5 px-6 py-4 flex justify-between items-center">
        <h1 className="text-xl font-normal tracking-tight">Color picker</h1>
        <button 
          onClick={() => fileInputRef.current?.click()}
          className="p-2 rounded-full hover:bg-black/5 transition-colors"
          title="Upload Photo"
        >
          <Plus className="w-6 h-6" />
        </button>
      </header>

      <main className="max-w-2xl mx-auto px-6 py-8">
        <section className="mb-12">
          <div 
            onClick={() => fileInputRef.current?.click()}
            className="group relative cursor-pointer overflow-hidden rounded-3xl bg-white border-2 border-dashed border-black/10 hover:border-yellow-400/50 transition-all duration-300 aspect-[16/9] flex flex-col items-center justify-center gap-4"
          >
            <div className="p-4 rounded-full bg-yellow-50 text-yellow-600 group-hover:scale-110 transition-transform duration-300">
              <Upload className="w-8 h-8" />
            </div>
            <div className="text-center">
              <p className="font-normal text-lg">Upload a photo</p>
              <p className="text-sm text-black/40">Tap to browse or take a picture</p>
            </div>
            <input 
              ref={fileInputRef}
              type="file" 
              accept="image/*" 
              className="hidden" 
              onChange={handleFileUpload}
            />
            
            {isUploading && (
              <div className="absolute inset-0 bg-white/80 backdrop-blur-sm flex items-center justify-center">
                <div className="flex flex-col items-center gap-3">
                  <div className="w-8 h-8 border-4 border-yellow-500 border-t-transparent rounded-full animate-spin" />
                  <p className="text-sm font-medium text-yellow-600">Extracting colors...</p>
                </div>
              </div>
            )}
          </div>
        </section>

        <section className="mb-8 space-y-4">
          <div className="flex flex-col sm:flex-row gap-4 items-center justify-between">
            <div className="relative w-full sm:w-64 group">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-black/20 group-focus-within:text-yellow-500 transition-colors" />
              <input 
                type="text"
                placeholder="Search palettes..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-10 pr-4 py-2 bg-white border border-black/5 rounded-2xl text-sm outline-none focus:border-yellow-500/50 transition-all shadow-sm"
              />
            </div>
            
            <div className="flex items-center bg-white border border-black/5 rounded-2xl p-1 shadow-sm">
              <button 
                onClick={() => setSortOrder('newest')}
                className={`px-4 py-1.5 text-xs font-medium rounded-xl transition-all ${sortOrder === 'newest' ? 'bg-black text-white shadow-md' : 'text-black/40 hover:text-black/60'}`}
              >
                Newest
              </button>
              <button 
                onClick={() => setSortOrder('oldest')}
                className={`px-4 py-1.5 text-xs font-medium rounded-xl transition-all ${sortOrder === 'oldest' ? 'bg-black text-white shadow-md' : 'text-black/40 hover:text-black/60'}`}
              >
                Oldest
              </button>
            </div>
          </div>
        </section>

        <section>
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-sm font-normal uppercase tracking-widest text-black/40">Your Collection</h2>
            <span className="text-xs font-mono text-black/30">{filteredAndSortedPalettes.length} visible</span>
          </div>

          <div className="space-y-8">
            <AnimatePresence mode="popLayout">
              {filteredAndSortedPalettes.map((palette) => (
                <PaletteCard 
                  key={palette.id}
                  palette={palette}
                  onDelete={deletePalette}
                  onUpdateName={updatePaletteName}
                  onCopy={handleCopy}
                />
              ))}
            </AnimatePresence>

            {filteredAndSortedPalettes.length === 0 && (
              <div className="py-20 text-center">
                <div className="inline-flex p-4 rounded-full bg-black/5 mb-4">
                  {searchQuery ? <Search className="w-8 h-8 text-black/20" /> : <Camera className="w-8 h-8 text-black/20" />}
                </div>
                <p className="text-black/40 font-medium">
                  {searchQuery ? 'No palettes match your search' : 'No palettes yet'}
                </p>
              </div>
            )}
          </div>
        </section>
      </main>

      <footer className="py-12 text-center border-t border-black/5 mt-12">
        <p className="text-xs text-black/20 font-mono">COLOR PICKER v1.1 • AMY MERY</p>
      </footer>
    </div>
  );
}
